[package]
name = "kancolle-a"
edition = "2021"
version.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
csv = "1.3.0"
derive-getters = "0.4.0"
itertools = "0.13.0"
lazy-static-include = "3.2.1"
regex = "1.10.6"
reqwest = { version = "0.12.5", features = ["blocking", "cookies"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
strum = { version = "0.26.3", features = ["derive"] }

[dev-dependencies]
chrono-tz = "0.9.0"
